import { FormEvent, useState } from "react";
import iconReview from "../assets/icons/spec-review.svg";
import iconLibrary from "../assets/icons/spec-library.svg";
import iconCollaborate from "../assets/icons/spec-collaborate.svg";
import iconSchoolContracted from "../assets/icons/spec-school-contracted.svg";
import iconParentDirect from "../assets/icons/spec-parent-direct.svg";
import accept1 from "../assets/icons/spec-accept-1.svg";
import accept2 from "../assets/icons/spec-accept-2.svg";
import accept3 from "../assets/icons/spec-accept-3.svg";
import accept4 from "../assets/icons/spec-accept-4.svg";
import accept5 from "../assets/icons/spec-accept-5.svg";
import accept6 from "../assets/icons/spec-accept-6.svg";

/** Figma: node 264:2747 "P-004 For Specialists" */

const ROLES = [
  {
    icon: iconReview,
    title: "Review AI strategies for safety",
    body: "Assess automated recommendations generated by our AI engine to ensure they are evidence-based, safe, and tailored to specific neuro-types.",
  },
  {
    icon: iconLibrary,
    title: "Contribute to the Evidence Library",
    body: "Submit white papers, clinical guides, and validated strategies to our central database, reaching thousands of educators and parents instantly.",
  },
  {
    icon: iconCollaborate,
    title: "Direct collaboration with families",
    body: "Provide micro-consultations or detailed feedback to parents and school teams through our secure, integrated messaging and case system.",
  },
];

const ENGAGEMENT = [
  {
    icon: iconSchoolContracted,
    title: "School-Contracted",
    chip: "bg-[#EFF6FF]",
    tick: "text-brand",
    items: [
      "Fixed fee per school audit or strategy review pack",
      "Regular monthly retainers for high-volume contributors",
      "Support whole-school neurodiversity initiatives",
      "Quarterly reporting on system-wide impact",
    ],
  },
  {
    icon: iconParentDirect,
    title: "Parent Direct",
    chip: "bg-[#FFF7ED]",
    tick: "text-amber",
    items: [
      "Pay-per-review for specific student profiles",
      "Direct micro-consulting session fees",
      "Instant payments via secure platform wallet",
      "Flexible hours—set your own availability",
    ],
  },
];

const ACCEPT = [
  { icon: accept1, label: "Tertiary qualification in relevant field" },
  { icon: accept2, label: "Professional registration (AHPRA, AASW, etc)" },
  { icon: accept3, label: "Current Working With Children Check (WWCC)" },
  { icon: accept4, label: "3+ years clinical/practical experience" },
  { icon: accept5, label: "Neurodiversity-affirming practice alignment" },
  { icon: accept6, label: "Commitment to non-clinical language" },
];

const CATEGORIES = [
  "Psychologist",
  "Occupational Therapist",
  "Speech Pathologist",
  "Behaviour Support Practitioner",
  "Social Worker",
  "Other",
];

const FIELD =
  "h-[42px] w-full rounded-md border border-line-edge bg-mist px-3 text-sm text-ink placeholder:text-footext focus:border-brand focus:bg-white focus:outline-none focus:ring-2 focus:ring-brand/20";
const LABEL =
  "pb-1.5 text-[11px] font-bold uppercase leading-4 tracking-[0.55px] text-subtle";

export default function ForSpecialistsPage() {
  const [submitted, setSubmitted] = useState(false);

  function handleSubmit(e: FormEvent) {
    e.preventDefault();
    // No backend for applications yet — acknowledge instead of failing silently.
    setSubmitted(true);
  }

  return (
    <>
      {/* ── Hero ─────────────────────────────────────────────── */}
      <section className="bg-white px-6 py-16 md:px-20 md:py-20">
        <div className="mx-auto grid max-w-shell items-center gap-12 lg:grid-cols-2">
          <div className="flex flex-col items-start">
            <span className="text-[11px] font-bold uppercase leading-[16.5px] tracking-[1.1px] text-amber">
              For Neurodiversity Specialists
            </span>

            <h1 className="pt-4 text-[34px] font-bold leading-[1.1] tracking-[-1.2px] text-ink md:text-5xl md:leading-[52.8px]">
              Amplify your impact,
              <br />
              beyond the consultation
              <br />
              room
            </h1>

            <p className="max-w-[560px] pt-6 text-base leading-[26px] text-body">
              Join a network of qualified professionals supporting
              neurodivergent learners. Review AI-generated strategies,
              contribute evidence to the curated library, and collaborate
              directly with families and schools.
            </p>

            <div className="flex flex-wrap gap-4 pt-8">
              <a
                href="#apply"
                className="flex h-12 items-center justify-center rounded-lg bg-brand px-6 text-base font-bold text-white shadow-btn transition-colors hover:bg-[#255d99]"
              >
                Apply to Join the Network
              </a>
              <button
                type="button"
                className="flex h-12 items-center justify-center rounded-lg border border-line-edge bg-white px-6 text-base font-bold text-brand transition-colors hover:bg-mist"
              >
                Download Specialist Pack
              </button>
            </div>
          </div>

          {/* Specialist console mockup */}
          <div className="w-full rounded-2xl border border-line-edge bg-white p-6 shadow-[0px_25px_50px_-12px_rgba(0,0,0,0.15)]">
            <div className="flex items-start justify-between gap-4">
              <div>
                <p className="text-[10px] font-bold uppercase leading-[15px] tracking-[0.5px] text-footext">
                  Welcome Back
                </p>
                <p className="pt-1 text-lg font-bold leading-7 text-ink">
                  Dr. Sarah Thompson
                </p>
              </div>
              <span
                aria-hidden
                className="flex size-8 items-center justify-center rounded-full bg-mist text-sm text-brand"
              >
                🔔
              </span>
            </div>

            <div className="mt-5 overflow-clip rounded-xl border border-line-edge">
              <div className="flex items-center justify-between bg-mist px-4 py-3">
                <span className="text-sm font-bold leading-5 text-ink">
                  Review Queue
                </span>
                <span className="rounded-full bg-[#D97706] px-2.5 py-0.5 text-[10px] font-bold uppercase leading-[15px] tracking-[0.5px] text-white">
                  4 New
                </span>
              </div>
              {[
                {
                  title: "Executive Function Strategy",
                  from: "Request from: Oakwood High",
                },
                {
                  title: "Sensory Profile Validation",
                  from: "Request from: Parent Direct",
                },
              ].map((r) => (
                <div
                  key={r.title}
                  className="flex items-center justify-between gap-4 border-t border-line-soft bg-white px-4 py-3"
                >
                  <span>
                    <span className="block text-sm font-semibold leading-5 text-ink">
                      {r.title}
                    </span>
                    <span className="block text-xs leading-4 text-muted">
                      {r.from}
                    </span>
                  </span>
                  <span aria-hidden className="text-muted">
                    ›
                  </span>
                </div>
              ))}
            </div>

            <div className="mt-4 grid grid-cols-2 gap-4">
              {[
                { label: "Library Contributions", value: "12" },
                { label: "Monthly Earnings", value: "$1,450" },
              ].map((s) => (
                <div
                  key={s.label}
                  className="flex flex-col gap-1 rounded-lg border border-line-soft bg-mist p-4"
                >
                  <span className="text-[10px] font-bold uppercase leading-[15px] tracking-[0.5px] text-footext">
                    {s.label}
                  </span>
                  <span className="text-2xl font-bold leading-8 text-brand">
                    {s.value}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── Your role on the platform ────────────────────────── */}
      <section className="bg-white px-6 pb-24 md:px-20">
        <div className="mx-auto flex max-w-shell flex-col gap-12">
          <div className="flex flex-col items-center gap-3">
            <h2 className="text-center text-3xl font-bold leading-10 tracking-[-1px] text-ink md:text-4xl">
              Your role on the platform
            </h2>
            <span aria-hidden className="h-1 w-16 rounded-full bg-amber" />
          </div>

          <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
            {ROLES.map((r) => (
              <article
                key={r.title}
                className="flex flex-col items-center gap-4 rounded-card border border-line-edge bg-white p-8 text-center"
              >
                <div className="flex size-12 items-center justify-center rounded-chip bg-brand">
                  <span className="size-5 overflow-clip">
                    <img src={r.icon} alt="" aria-hidden className="size-full" />
                  </span>
                </div>
                <h3 className="text-lg font-bold leading-7 text-ink">
                  {r.title}
                </h3>
                <p className="text-[13px] leading-[21px] text-muted">
                  {r.body}
                </p>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* ── Two ways to engage ───────────────────────────────── */}
      <section className="bg-panel px-6 py-20 md:px-20">
        <div className="mx-auto flex max-w-shell flex-col gap-10">
          <h2 className="text-center text-3xl font-bold leading-10 tracking-[-1px] text-ink md:text-4xl">
            Two ways to engage
          </h2>

          <div className="mx-auto grid w-full max-w-4xl gap-8 md:grid-cols-2">
            {ENGAGEMENT.map((e) => (
              <article
                key={e.title}
                className="flex flex-col gap-5 rounded-card border border-line-edge bg-white p-8"
              >
                <div className="flex items-center gap-3">
                  <span
                    className={`flex size-8 items-center justify-center rounded-lg ${e.chip}`}
                  >
                    <span className="size-4 overflow-clip">
                      <img
                        src={e.icon}
                        alt=""
                        aria-hidden
                        className="size-full"
                      />
                    </span>
                  </span>
                  <h3 className="text-xl font-bold leading-8 text-ink">
                    {e.title}
                  </h3>
                </div>
                <ul className="flex flex-col gap-3">
                  {e.items.map((i) => (
                    <li
                      key={i}
                      className="flex items-start gap-2.5 text-[13px] leading-5 text-body"
                    >
                      <span aria-hidden className={e.tick}>
                        ✓
                      </span>
                      {i}
                    </li>
                  ))}
                </ul>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* ── Who we accept ────────────────────────────────────── */}
      <section className="bg-white px-6 py-20 md:px-20">
        <div className="mx-auto flex max-w-shell flex-col gap-10">
          <h2 className="text-center text-3xl font-bold leading-10 tracking-[-1px] text-ink md:text-4xl">
            Who we accept
          </h2>

          <div className="mx-auto grid w-full max-w-4xl gap-4 md:grid-cols-2">
            {ACCEPT.map((a) => (
              <div
                key={a.label}
                className="flex items-center gap-3 rounded-lg bg-[#EFF6FF] px-4 py-3.5"
              >
                <span className="size-5 shrink-0 overflow-clip">
                  <img src={a.icon} alt="" aria-hidden className="size-full" />
                </span>
                <span className="text-[13px] font-medium leading-5 text-subtle">
                  {a.label}
                </span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Application form ─────────────────────────────────── */}
      <section id="apply" className="bg-panel px-6 py-20 md:px-20">
        <div className="mx-auto max-w-[720px]">
          <div className="rounded-card bg-white p-8 shadow-card md:p-12">
            <div className="flex flex-col gap-2 pb-8 text-center">
              <h2 className="text-3xl font-bold leading-9 text-ink">
                Apply to join the network
              </h2>
              <p className="text-[13px] leading-5 text-muted">
                Our team will review your application within 3-5 business days.
              </p>
            </div>

            <form onSubmit={handleSubmit} className="flex flex-col gap-5">
              <div className="grid gap-5 sm:grid-cols-2">
                <label className="flex flex-col">
                  <span className={LABEL}>First Name</span>
                  <input required className={FIELD} placeholder="Jane" />
                </label>
                <label className="flex flex-col">
                  <span className={LABEL}>Last Name</span>
                  <input required className={FIELD} placeholder="Doe" />
                </label>
              </div>

              <label className="flex flex-col">
                <span className={LABEL}>Email Address</span>
                <input
                  required
                  type="email"
                  className={FIELD}
                  placeholder="jane@practice.com"
                />
              </label>

              <div className="grid gap-5 sm:grid-cols-2">
                <label className="flex flex-col">
                  <span className={LABEL}>Professional Category</span>
                  <select className={FIELD} defaultValue={CATEGORIES[0]}>
                    {CATEGORIES.map((c) => (
                      <option key={c}>{c}</option>
                    ))}
                  </select>
                </label>
                <label className="flex flex-col">
                  <span className={LABEL}>Registration Number</span>
                  <input className={FIELD} placeholder="AHPRA PSY000..." />
                </label>
                <label className="flex flex-col">
                  <span className={LABEL}>Years of Experience</span>
                  <input className={FIELD} placeholder="e.g. 5" />
                </label>
                <label className="flex flex-col">
                  <span className={LABEL}>LinkedIn Profile URL</span>
                  <input
                    className={FIELD}
                    placeholder="linkedin.com/in/username"
                  />
                </label>
              </div>

              <label className="flex flex-col">
                <span className={LABEL}>Brief Professional Bio</span>
                <textarea
                  rows={4}
                  className="w-full rounded-md border border-line-edge bg-mist px-3 py-2.5 text-sm text-ink placeholder:text-footext focus:border-brand focus:bg-white focus:outline-none focus:ring-2 focus:ring-brand/20"
                  placeholder="Tell us about your specialization..."
                />
              </label>

              <div className="grid gap-4 sm:grid-cols-3">
                {["CV/Resume", "Registration", "WWCC Proof"].map((u) => (
                  <button
                    key={u}
                    type="button"
                    className="flex flex-col items-center gap-1.5 rounded-lg border border-dashed border-line-strong bg-white px-4 py-4 text-[11px] font-bold uppercase tracking-[0.55px] text-muted transition-colors hover:border-brand hover:text-brand"
                  >
                    <span aria-hidden className="text-base">
                      ⬆
                    </span>
                    {u}
                  </button>
                ))}
              </div>

              {submitted && (
                <p
                  role="status"
                  className="rounded-lg border border-teal-border bg-teal-tint px-4 py-3 text-sm leading-5 text-teal"
                >
                  Thanks — the specialist network isn't open for applications
                  yet. We'll start reviewing alongside the MiZanova launch.
                </p>
              )}

              <button
                type="submit"
                className="flex h-12 items-center justify-center rounded-lg bg-brand text-base font-bold text-white shadow-btn transition-colors hover:bg-[#255d99]"
              >
                Submit Application
              </button>
            </form>
          </div>
        </div>
      </section>
    </>
  );
}
